### PR TITLE
More gateway fixes.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by tedivm** [comment]
Can you describe what's going on here?

**Comment by ahmedcharles** [comment]
I added some comments in the source to help explain to people reading it next time.

After the last fix, I noticed that walls stopped being built, so I added some logging and noticed that it was trying to build within 1 square of an exit, diagonally. So, most of this is to fix that. There's some aesthetic changes for mixing walls and ramparts that can potentially result in a completely walled off exit, but I suspect that given how long this has gone without working, that risk isn't much of an issue.

**Comment by tedivm** [comment]
Did you do a visual on the walls that show up? Any chance you can screenshot the visual and show it?

**Comment by ahmedcharles** [comment]
http://prntscr.com/j5else

**Pull request merged**
