### PR TITLE
restructure getSuicideBooth

### PR DESCRIPTION
**Pull request by screeps-automated-user**
fixes a breaking error when no spawn can be found.

### CODE REVIEW

**Comment by JestDotty** [comment]
`if([])` is true

do `if([].length)` instead

**Comment by JestDotty** [comment]
... and upon reading the file there was nothing wrong with the old code =X

you can do `array[23]` on an empty array and it will be happy, and return `undefined` for your element

`undefiend` is viewed as false by js, so the later `!spawn` catches it: https://github.com/screeps-automated-user/screeps-quorum/blob/ba0be7dbb6a09e506439b32aeac47c47caa6b4fe/src/extends/room/landmarks.js#L11

**Comment by screeps-automated-user** [comment]
I'm not entirely sure how to recreate, but try removing all spawns from a room. It displayed a big error for me, which is why I did the extra check..

**Comment by JestDotty** [comment]
might be from this @ 138: https://github.com/ScreepsQuorum/screeps-quorum/blob/1d3d427ee24437e50199ec9ecd94b5160ea169d0/src/extends/creep/actions.js#L133-L138

keep the error logs =X

**Comment by screeps-automated-user** [comment]
I should've kept the log, you're absolutely right on that... The error that showed did reference line 133 of `actions`, and then failed on line 8 in `landmarks` (he really wasn't happy about calling the "first" of `this.structures[STRUCTURE_SPAWN]` as it wasn't an array.. I'm not sure if the action continued or just failed in total, but in general.. error != happy)

I can't remember an error/reference in the error about line 138 of `actions`, although it would seem like that would fail (`spawn.recycleCreep` wouldn't be callable?)

**Comment by tedivm** [comment]
@JestDotty - you can do `array[23]` but you can't do `undefined[23]`, which is what is being prevented here.

This is also why @screeps-automated-user's first code was correct (checking that the array existed), but this new code isn't. `array.length` may return zero, but `undefined.length` will return an error.

The best answer would be to do both the original check and then after that the length check. @screeps-automated-user, can you update this PR to do that?

**Comment by JestDotty** [comment]
bizarre/confusing it would return undefined instead of an empty array... but just my opinion...

**Comment by tedivm** [comment]
The `Room.structures` object currently gets generated by iterating though all the objects in the room. If there are no structures of a specific type then the `structures` object doesn't have a field for it.

If you think it should behave differently you can make a pull request. The relevant code is [here](https://github.com/ScreepsQuorum/screeps-quorum/blob/master/src/extends/room/structures.js).

**Comment by screeps-automated-user** [comment]
@tedivm Please let me know if this is the correct/most efficient solution

**Comment by tedivm** [comment]
Yeah, looks good to me!

**Pull request merged**
