### PR TITLE
Merge Faster

### PR DESCRIPTION
**Pull request by ags131**
Who wants to wait a whole 24 hours for it to merge? ~6~ 12 hours is much quicker :)

### CODE REVIEW

**Comment by tedivm** [comment]
I'm not sure this will actually work with gitconsensus.

**Comment by tedivm** [comment]
I dislike the idea of someone making a pull request while I'm sleeping and it merging before I wake up.

**Comment by ags131** [comment]
Now 12 hours, much less likely to appear and merge while asleep ;)

**Comment by tedivm** [comment]
Can you switch this to hours instead of days to match your pull request on gitconsensus? Otherwise if I merge that and set it up this will mean the pull request gets pulled in 30 minutes.

**Comment by tedivm** [comment]
One more request- can you add a field `version: 2`. I'm going to set gitconsensus so that if it doesn't see a version field it will convert the merge_delay field from days to hours, but if it seems the version field and it's set to `2` it'll just assume it's already in hours. This will give us backwards compatibility and make sure that nothing gets accidentally pulled during the transition.

**Comment by ags131** [comment]
Added :)

**Pull request merged**
