### PR TITLE
Make the 'tick summary' logging slightly less verbose.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by tedivm** [comment]
I'm downvoting because I think that this will be really hard to read without newlines between each stat type.

**Comment by ahmedcharles** [comment]
Updated to make it optional, as per the discussion on slack.

**Comment by tedivm** [comment]
New optional version is much better so I shifted my vote.

**Comment by semperrabbit** [comment]
upvoted after change

**Comment by ahmedcharles** [comment]
This consensus thing is working better than I initially imagined. That's cool.

**Pull request merged**
