### PR TITLE
Removed signController method from spook role

### PR DESCRIPTION
**Pull request by admon84**
This will minimize controller signing to owned rooms.

### CODE REVIEW

**Comment by ags131** [comment]
I'm against removing it completely, however, filtering it to only Quorum claimed/reserved rooms would be fine

**Comment by tedivm** [comment]
Neutral rooms or rooms that haven't been signed in weeks should also be signed in my opinion, but yeah.

**Comment by semperrabbit** [comment]
concur with ags and tedivm. if you added everything back, and added the following in between lines 84 and 85, I'd upvote...
```if(!creep.room.controller.my && creep.room.controller.reservation.username !== USERNAME) {
  return false
}```

**Comment by tedivm** [comment]
I think we should sign more than just Quorum's own rooms- neutral rooms are great to sign, as are rooms which haven't been signed in a long time (a month?)

**Comment by semperrabbit** [comment]
idk, I could see how that could be viewed as annoying. I do not sign my controllers in either owned or reserved rooms. I would be annoyed by a neighboring quorum signing my reserved rooms, simply because I didn't put the effort into writing code to sign my own.

**Comment by tedivm** [comment]
What if it was limited to a certain distance from an existing room?

**Comment by OrletSoir** [comment]
> concur with ags and tedivm. if you added everything back, and added the following in between lines 84 and 85, I'd upvote...
> `if(!creep.room.controller.my && creep.room.controller.reservation.username !== USERNAME) { return false }`

This would cause errors in rooms claimed by others. Should be `if(!creep.room.controller.my && creep.room.controller.reservation && creep.room.controller.reservation.username !== USERNAME) { return false }`

**Pull request closed without merging**
