### PR TITLE
Boundingbox in roompositions

### PR DESCRIPTION
**Pull request by ButAds**
Added a function to create a bounding box for us within the room borders.
Avoids code duplication.

### CODE REVIEW

**Comment by ButAds** [comment]
Integrated unit tests from postcrafters PR, used those to fix the method

**Comment by PostCrafter** [comment]
FYI: I'm currently trying to integrate [ava-check](https://www.npmjs.com/package/ava-check) for generative testing, so the tests don't rely on the numbers specified and the tests gets combined into a single one.
Unfortunately this tool seems to be broken at the moment (https://github.com/leebyron/testcheck-js/issues/47) and the fix (https://github.com/leebyron/testcheck-js/pull/48) is pending with some failing tests for quite a while already.
I'll see if I can get the issue resolved or build a solution directly on top of testcheck-js instead of the ava integration.

**Comment by tedivm** [comment]
We've reached the point where we have unit tests? That's awesome.

**Comment by ViezeVingertjes** [comment]
And the point where we get merge conflicts! haha.

**Comment by ButAds** [comment]
Fixed merge conflicts

**Pull request merged**
