### PR TITLE
Source link fix

### PR DESCRIPTION
**Pull request by duckymirror**
When a source is near the room controller the link built for the controller is recognized as the link for the source (See [room W27S1 on shard2](https://screeps.com/a/#!/room/shard2/W27S1)).

### CODE REVIEW

**Comment by ahmedcharles** [comment]
Wouldn't it be better to have it used by the controller and the source?

**Comment by duckymirror** [comment]
I think there would be conflicts when it is a controller link which gets energy transferred to it and a source link which transfers energy away. Also as you can see in the room mentioned the controller link isn't reached by the miner and it drops its energy to the ground. I believe this is the most efficient solution.

**Comment by ahmedcharles** [comment]
It certainly would require more changes, like moving where the miner is located. I believe this is a great example of a peephole optimization, though that's typically about compilers: https://en.wikipedia.org/wiki/Peephole_optimization

**Comment by duckymirror** [comment]
This is probably a better way than mine... As soon as I find time again I'll try to implement that.

**Pull request closed without merging**
